libxl/arm: initialize size to fix compilation error in gcc 6.2
 In file included from libxl_arm.h:17:0,
                  from libxl_arm_acpi.c:19:
 libxl_arm_acpi.c: In function 'libxl__get_acpi_size':
 libxl_internal.h:129:44: error: 'size' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      (((unsigned long)(_val)+(1UL<<(_order))-1) & ~((1UL<<(_order))-1))
                                             ^
 libxl_arm_acpi.c:101:14: note: 'size' was declared here
      uint64_t size;
               ^~~~
 In file included from libxl_arm.h:17:0,
                  from libxl_arm_acpi.c:19:
 libxl_arm_acpi.c: In function 'libxl__prepare_acpi':
 libxl_internal.h:129:44: error: 'size' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      (((unsigned long)(_val)+(1UL<<(_order))-1) & ~((1UL<<(_order))-1))
                                             ^
 libxl_arm_acpi.c:126:12: note: 'size' was declared here
      size_t size;
             ^~~~

Signed-off-by: Octavian Purdila <octavian.purdila@nxp.com>
(cherry picked from commit 0ab676389320e99797f1ce0fa5c967f6e50292af)